main: redlime.fishing.Main
name: FishingRodKnockback
version: '1.7.0'
description: Added fishing rod knockback at 1.8.9 version
author: RedLime
authors: [B4TT3RY__ (Support), Mathshyun, iShadey]
loadafter:
  - ViaVersion
  - ProtocolSupport
  - OldCombatMechanics
commands:
  fishingknockback:
    aliases: fkb
    permission: fishingkb.admin
    permission-message: You don't have permission :(
    description: plugin's info