main: redlime.fishing.Main
name: FishingRodKnockback
version: '1.8.1'
description: Added fishing rod knockback at 1.8.9 version
author: RedLime
authors: [B4TT3RY__ (Support), Mathshyun, iShadey]
softdepend: [ViaVersion, ProtocolSupport, OldCombatMechanics, WorldGuard]
commands:
  fishingknockback:
    aliases: fkb
    permission: fishingkb.admin
    permission-message: You don't have permission :(
    description: plugin's info